import { SEO } from "@/components/SEO";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { FileText, AlertTriangle, Shield, CreditCard, Scale, Users, Settings, Mail } from "lucide-react";

export default function TermsAndConditions() {
  return (
    <>
      <SEO
        title="Terms and Conditions | FelixaTouch - Clinic Management Software"
        description="FelixaTouch Terms and Conditions - Read our terms of service for using FelixaTouch clinic management software. Understand your rights, responsibilities, and our service policies."
        url="/terms-and-conditions"
      />

      <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white dark:from-slate-950 dark:to-slate-900">
        <Header />

        <main className="py-16 md:py-24">
          <div className="container mx-auto px-4 md:px-6 max-w-4xl">
            {/* Header */}
            <div className="text-center mb-12">
              <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-blue-600 to-purple-600 rounded-2xl mb-6">
                <FileText className="w-8 h-8 text-white" />
              </div>
              <h1 className="text-4xl md:text-5xl font-black text-slate-900 dark:text-white mb-4">
                Terms & Conditions
              </h1>
              <p className="text-lg text-slate-600 dark:text-slate-400">
                Please read these terms carefully before using FelixaTouch
              </p>
            </div>

            {/* Content */}
            <div className="prose prose-slate dark:prose-invert max-w-none">
              {/* 1. Introduction */}
              <section className="mb-12 bg-slate-50 dark:bg-slate-800/50 rounded-xl p-6 md:p-8">
                <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-6 flex items-center gap-3">
                  <FileText className="w-6 h-6 text-blue-600" />
                  1. Introduction
                </h2>
                
                <p className="text-slate-700 dark:text-slate-300 mb-4">
                  FelixaTouch is a website and mobile application owned and managed by IntPurple Technologies LLP ("IntPurple Technologies LLP", "We", "Us" and/or "Our").
                </p>

                <p className="text-slate-700 dark:text-slate-300 mb-4">
                  These terms and conditions ("Terms" and "Agreement") are applicable to the use of FelixaTouch available in the form of a website at <a href="https://www.felixatouch.com" className="text-brand-primary hover:underline font-semibold">www.felixatouch.com</a> and application, and any of our websites, products and/or services that explicitly indicate the applicability of these Terms (collectively, "Service(s)"), by you ("You", "Your", "User" and/or "Customer"). Please read this document carefully and ensure that You understand its contents before using Our Service(s).
                </p>

                <div className="bg-gradient-to-br from-blue-50 to-purple-50 dark:from-blue-950/20 dark:to-purple-950/20 rounded-lg p-6 mt-6">
                  <h3 className="font-black text-slate-900 dark:text-white mb-4">About FelixaTouch</h3>
                  <p className="text-slate-700 dark:text-slate-300 text-sm">
                    FelixaTouch is an app owned and managed by IntPurple Technologies to provide a method for communication between Users, and automated analysis of data. Communications between Users of the Service are inaccessible to IntPurple Technologies LLP. Certain data provided by Users may be analysed by the Service to provide a report. The reports generated by the Service are provided for aiding Users in their tasks only. These reports do not form medical opinion or medical advice, and are subject to final review, approval or modification by the User. The final diagnosis/feedback provided by Users is used to train the artificial intelligence in order to provide better results in future.
                  </p>
                </div>

                <div className="bg-white dark:bg-slate-900 rounded-lg p-6 mt-6 border-l-4 border-brand-primary">
                  <h3 className="font-black text-slate-900 dark:text-white mb-4">Key Requirements</h3>
                  <ul className="space-y-2 text-slate-700 dark:text-slate-300 text-sm">
                    <li className="flex items-start gap-2">
                      <span className="text-brand-primary mt-1">✓</span>
                      <span>You must be a registered and licensed medical professional in your jurisdiction</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-emerald-600 mt-1">✓</span>
                      <span>You must be at least 18 years old and capable of giving a valid consent</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-purple-600 mt-1">✓</span>
                      <span>You are responsible for everything that happens through the use of Your account</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-orange-600 mt-1">✓</span>
                      <span>Misuse of Services, abuse of Services and illegal behaviour are strictly prohibited</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-blue-600 mt-1">✓</span>
                      <span>Use of the Service on behalf of another person is strictly prohibited</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-pink-600 mt-1">✓</span>
                      <span>Payment gateway charges, bank charges and taxes must be borne by You</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-red-600 mt-1">✓</span>
                      <span>All payments must be made on time</span>
                    </li>
                  </ul>
                </div>

                <div className="bg-amber-50 dark:bg-amber-950/20 rounded-lg p-6 mt-6 border border-amber-200 dark:border-amber-800">
                  <h3 className="font-black text-amber-900 dark:text-amber-400 mb-3 flex items-center gap-2">
                    <AlertTriangle className="w-5 h-5" />
                    By Using This Service, You Agree To:
                  </h3>
                  <ul className="space-y-2 text-slate-700 dark:text-slate-300 text-sm">
                    <li>• Explicitly accepting these Terms such as by ticking a checkbox</li>
                    <li>• Accessing the Service</li>
                    <li>• Creating an account on the Service</li>
                    <li>• Accessing an account on the Service</li>
                    <li>• Placing an order or making a payment</li>
                    <li>• Undertaking any other action that involves interacting with the Service</li>
                  </ul>
                </div>

                <p className="text-slate-700 dark:text-slate-300 mt-6">
                  The collection, use, storage, processing, transfer, and deletion of Your personal information is governed by the <a href="/privacy-policy-2" className="text-brand-primary hover:underline font-semibold">"Privacy Policy"</a>.
                </p>
              </section>

              {/* 2. Access and Use of Service */}
              <section className="mb-12">
                <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-6 flex items-center gap-3">
                  <Users className="w-6 h-6 text-emerald-600" />
                  2. Access and Use of Service
                </h2>

                <div className="space-y-6">
                  <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Age and Competence</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      The Service is not intended for anyone under 18 years of age. Please do not use this Service if You are less than 18 years of age or otherwise not legally competent to accept this agreement. You must be a registered medical professional in your jurisdiction, and Your jurisdiction must permit the use of Service. If your jurisdiction requires the Service to be registered, You agree not use the Service. If in doubt, You must contact Us prior to using the Service.
                    </p>
                  </div>

                  <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Usage Limits</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      We may, at our sole discretion and without any notice, place technical or non-technical limitations on the use of the Service. We may change such usage limits from time to time.
                    </p>
                  </div>

                  <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Service Availability</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      We will do our utmost to ensure the availability and reliability of the Service, however due to the nature of the Internet, we cannot guarantee that Your use of the Service will be secure or error free, or that the Service will remain available.
                    </p>
                  </div>

                  <div className="bg-gradient-to-br from-red-50 to-orange-50 dark:from-red-950/20 dark:to-orange-950/20 rounded-lg p-6 border-2 border-red-200 dark:border-red-800">
                    <h3 className="font-semibold text-red-900 dark:text-red-400 mb-3 flex items-center gap-2">
                      <AlertTriangle className="w-5 h-5" />
                      Accuracy and Reliability of Information - CRITICAL
                    </h3>
                    <p className="text-slate-700 dark:text-slate-300 text-sm mb-3">
                      The detections and analysis performed by this Service, and the outcomes provided by this Service, are based on artificial intelligence that has been trained on similar medical issues. This means that the detections and analysis are performed by a computer, and not by a trained medical professional.
                    </p>
                    <p className="text-red-900 dark:text-red-400 text-sm font-semibold">
                      Outputs of this Service are NOT medical advice, and may be incorrect or inaccurate. The analysis performed by this Service must be used for the purpose of aiding trained medical professionals in the performance of their duties only. The analysis performed by this Service cannot be used for any medical procedure or medical advice without being verified by a trained medical professional.
                    </p>
                  </div>

                  <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Third Party Content</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      The Service may include content posted or made available by third parties (including but not limited to other users of the Service). You specifically agree that We are not responsible for any content sent using, posted on and/or otherwise made available by any third party.
                    </p>
                  </div>

                  <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Links to Third Party Websites</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      The Service may include links to third party websites, apps or services ("External Services"). External Services may collect your personal information subject to their own practices and privacy policies. We are not responsible for Your interactions with external services, and the activities of external services.
                    </p>
                  </div>

                  <div className="bg-amber-50 dark:bg-amber-950/20 rounded-lg p-6 border border-amber-200 dark:border-amber-800">
                    <h3 className="font-semibold text-amber-900 dark:text-amber-400 mb-3 flex items-center gap-2">
                      <AlertTriangle className="w-5 h-5" />
                      Beta Services
                    </h3>
                    <p className="text-slate-700 dark:text-slate-300 text-sm mb-3">
                      We may occasionally offer Beta Services for testing and feedback. Beta Services are NOT provided for general use and must not be relied upon for any reason. All data provided through Beta Services is subject to destruction at any time without prior notice.
                    </p>
                    <p className="text-amber-900 dark:text-amber-400 text-sm font-semibold">
                      If you choose to use Beta Services, You agree that We shall not be liable for any loss or damage of any kind, including but not limited to loss of data, loss of reputation, loss of income, or any other loss or damage. All risks associated with Beta Services shall be borne solely by the User.
                    </p>
                  </div>
                </div>
              </section>

              {/* 3. Customer Responsibilities */}
              <section className="mb-12 bg-slate-50 dark:bg-slate-800/50 rounded-xl p-6 md:p-8">
                <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-6 flex items-center gap-3">
                  <Shield className="w-6 h-6 text-purple-600" />
                  3. Customer Responsibilities
                </h2>

                <div className="space-y-6">
                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Accounts</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      You are responsible for ensuring the safety and security of Your account, including keeping Your login credentials secure. You are responsible for all activities that occur in Your account.
                    </p>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Accuracy of Information</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      You agree to provide and maintain true, accurate, current and complete information about You.
                    </p>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Responsibility for Payments</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      You are responsible for timely payments in accordance with "Payments and Refunds" below.
                    </p>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Legality of Your Use</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm mb-3">
                      You are responsible for ensuring that Your use of the Service does not violate any law. Additionally, You must not host, display, upload, modify, publish, transmit, update or share any information that:
                    </p>
                    <ul className="space-y-1 text-slate-600 dark:text-slate-400 text-sm ml-4">
                      <li>• Belongs to another person and to which You do not have any right</li>
                      <li>• Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, or libellous</li>
                      <li>• Harms minors in any way</li>
                      <li>• Infringes any patent, trademark, copyright or other proprietary rights</li>
                      <li>• Violates any law, rules or regulations</li>
                      <li>• Contains software viruses or any other malicious code</li>
                      <li>• Threatens national security or public order</li>
                      <li>• Consists of commercial solicitation, mass messaging, or any form of spam</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Misuse, Abusive Use and Excessive Use</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm mb-3">
                      You must not undertake any of the following:
                    </p>
                    <ul className="space-y-1 text-slate-600 dark:text-slate-400 text-sm ml-4">
                      <li>• Imposing unreasonable load on the Service infrastructure</li>
                      <li>• Abusive or excessive usage that affects other users</li>
                      <li>• Attempting to access the Service through unauthorized methods</li>
                      <li>• Intentionally causing errors or issues</li>
                      <li>• Sharing an account between multiple people</li>
                      <li>• Scanning for vulnerabilities except to report them to Us</li>
                      <li>• Attempting to extract information from the Service</li>
                      <li>• Circumventing usage limits</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Third Party Information</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      You are responsible for ensuring that You have the necessary rights to use the Service and to provide information to Us. You must not provide any personal information regarding any third party without appropriate prior written authorization.
                    </p>
                  </div>

                  <div className="bg-red-50 dark:bg-red-950/20 rounded-lg p-4 border border-red-200 dark:border-red-800">
                    <h3 className="font-semibold text-red-900 dark:text-red-400 mb-2">Legal Action by Us</h3>
                    <p className="text-slate-700 dark:text-slate-300 text-sm">
                      We reserve the right to initiate and/or undertake any civil and/or criminal action for breach of Customer Responsibilities.
                    </p>
                  </div>
                </div>
              </section>

              {/* 4. Payments & Refunds */}
              <section className="mb-12">
                <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-6 flex items-center gap-3">
                  <CreditCard className="w-6 h-6 text-blue-600" />
                  4. Payments & Refunds
                </h2>

                <div className="space-y-6">
                  <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Payments</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      If a payment is required to use the Service, You undertake to make all payments in a timely manner. Failure to make any payment on time may result in suspension or termination of this Agreement, Your account, and/or Your ability to access the Service.
                    </p>
                  </div>

                  <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Changes in Price</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      We reserve the right to, at any time, in our sole discretion and without prior notification, modify the price of any Service offered by Us.
                    </p>
                  </div>

                  <div className="bg-red-50 dark:bg-red-950/20 rounded-lg p-6 border border-red-200 dark:border-red-800">
                    <h3 className="font-semibold text-red-900 dark:text-red-400 mb-3">No Chargeback</h3>
                    <p className="text-slate-700 dark:text-slate-300 text-sm">
                      Chargebacks are strictly prohibited under these Terms. Initiation of a chargeback may result in suspension or termination of this Agreement, Your account, or the Service.
                    </p>
                  </div>

                  <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Cancellation</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      Cancellations are not permitted under this Agreement.
                    </p>
                  </div>

                  <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Refunds</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm mb-3">
                      Refunds may only be provided if they are applicable under the terms of this Agreement. Refunds will not include any taxes, payment processing fees, or other charges. The refund for payment made to a third party (e.g., Hospitals, Clinics or Doctors) is at the sole discretion of the third party.
                    </p>
                  </div>

                  <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Taxes, Charges and Fees</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      You shall be responsible for payment of all fees, costs and charges, and You agree to bear any and all applicable taxes, charges and fees, including sales tax, VAT, service tax, payment gateway charges, etc. You agree to pay all such taxes and charges without withholding or deduction.
                    </p>
                  </div>

                  <div className="bg-amber-50 dark:bg-amber-950/20 rounded-lg p-6 border border-amber-200 dark:border-amber-800">
                    <h3 className="font-semibold text-amber-900 dark:text-amber-400 mb-3">Exclusive Remedy</h3>
                    <p className="text-slate-700 dark:text-slate-300 text-sm">
                      This Section on Payments and Refunds provides Your sole remedy and Our sole responsibility for situations covered by this Section. This Section forms an essential basis for the Agreement.
                    </p>
                  </div>
                </div>
              </section>

              {/* 5-10 Additional Sections - Condensed for brevity */}
              <section className="mb-12">
                <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-4">5. Intellectual Property Rights</h2>
                <p className="text-slate-700 dark:text-slate-300 mb-4">
                  All Materials (Service content, incorporated materials, and outputs) are protected by intellectual property rights. You grant Us a worldwide, royalty-free license to use any information and data you provide in accordance with these Terms and the Privacy Policy.
                </p>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-4">6. Modifications</h2>
                <p className="text-slate-700 dark:text-slate-300">
                  We may modify this Agreement, the Service, or charges and fees at any time. We will post any modifications on this page with an updated date.
                </p>
              </section>

              <section className="mb-12 bg-red-50 dark:bg-red-950/20 rounded-xl p-6 md:p-8 border-2 border-red-200 dark:border-red-800">
                <h2 className="text-2xl font-black text-red-900 dark:text-red-400 mb-4">7. Warranty Disclaimers & Limitation of Liability</h2>
                <div className="space-y-4 text-slate-700 dark:text-slate-300">
                  <p>
                    <strong>The Service is provided "AS IS" and "AS AVAILABLE".</strong> We expressly disclaim all warranties of any kind. Content and free services are provided "as is" exclusive of any warranty whatsoever.
                  </p>
                  <p className="font-semibold text-red-900 dark:text-red-400">
                    You specifically acknowledge that the Service does not provide a medical diagnosis, and may provide incorrect analysis. The Service must be used by trained, registered and licensed medical professionals only. We shall not be liable for any death, injury, or any other loss or damage caused as a result of reliance upon any analysis provided by the Service.
                  </p>
                  <p>
                    In no situation shall Our liability exceed the total amount paid by You for the services in the three (3) months preceding the incident, or INR Five Hundred (500), whichever is higher.
                  </p>
                </div>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-4">8. Indemnification</h2>
                <p className="text-slate-700 dark:text-slate-300">
                  You agree to indemnify and hold Us harmless from any claim, losses, or damages arising out of unauthorized access using Your login credentials, breach of these Terms, or use beyond the intended scope.
                </p>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-4">9. Terms and Termination</h2>
                <p className="text-slate-700 dark:text-slate-300">
                  This Agreement commences when you first accept it and continues until terminated by either party. We may terminate at any time with or without cause. You may terminate by contacting us to deactivate Your account.
                </p>
              </section>

              {/* 9. Cancellation and Refund Policy */}
              <section className="mb-12 bg-gradient-to-br from-blue-50 to-purple-50 dark:from-blue-950/20 dark:to-purple-950/20 rounded-xl p-6 md:p-8">
                <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-6">9. Cancellation and Refund Policy</h2>
                
                <div className="space-y-6">
                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">1. Subscription Cancellation</h3>
                    <ul className="space-y-2 text-slate-700 dark:text-slate-300 text-sm">
                      <li>• Users can cancel their FelixaTouch subscription at any time from their account dashboard or by contacting support</li>
                      <li>• Cancellation will be effective at the <strong>end of the current billing cycle</strong></li>
                      <li>• Once cancelled, users will continue to have access to all features until their subscription period expires</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">2. Refund Eligibility</h3>
                    <p className="text-slate-700 dark:text-slate-300 text-sm mb-3">
                      Because Felixatouch provides digital software services, refunds are generally not issued after payment is completed. However, refunds may be granted under specific circumstances such as:
                    </p>
                    <ul className="space-y-2 text-slate-700 dark:text-slate-300 text-sm">
                      <li>• Accidental duplicate payment</li>
                      <li>• Technical issues on our end that prevent you from accessing the service</li>
                      <li>• Any other valid reason approved at the discretion of the Felixatouch management team</li>
                    </ul>
                    <p className="text-slate-700 dark:text-slate-300 text-sm mt-3">
                      Refund requests must be submitted within <strong>7 days of the transaction date</strong>.
                    </p>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">3. Trial and Demo Policy</h3>
                    <p className="text-slate-700 dark:text-slate-300 text-sm">
                      We encourage users to <strong>book a demo</strong> or use any available <strong>trial version</strong> before purchasing. This ensures that you fully understand the product's features and suitability for your clinic's needs.
                    </p>
                  </div>

                  <div className="bg-red-50 dark:bg-red-950/20 rounded-lg p-5 border border-red-200 dark:border-red-800">
                    <h3 className="font-semibold text-red-900 dark:text-red-400 mb-3">4. No Refund for Change of Mind</h3>
                    <p className="text-slate-700 dark:text-slate-300 text-sm mb-2">
                      Once access to the software is granted, <strong>no refund</strong> will be provided for reasons such as:
                    </p>
                    <ul className="space-y-1 text-slate-700 dark:text-slate-300 text-sm">
                      <li>• Change of preference</li>
                      <li>• Lack of usage</li>
                      <li>• Misunderstanding of features after purchase (unless demonstrably unclear from our side)</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">5. How to Request a Refund</h3>
                    <p className="text-slate-700 dark:text-slate-300 text-sm mb-3">
                      To request a refund, please contact: <a href="mailto:contact@intpurple.com" className="text-brand-primary hover:underline font-semibold">contact@intpurple.com</a>
                    </p>
                    <p className="text-slate-700 dark:text-slate-300 text-sm">
                      Include your registered email, payment details, and the reason for your request. Our team will review and respond within <strong>5–7 business days</strong>.
                    </p>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">6. Modifications</h3>
                    <p className="text-slate-700 dark:text-slate-300 text-sm">
                      FelixaTouch reserves the right to update or modify this Cancellation and Refund Policy at any time. Any changes will be posted on this page, and continued use of our services will signify your acceptance of those changes.
                    </p>
                  </div>
                </div>
              </section>

              {/* 10. General Provisions */}
              <section className="mb-12">
                <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-6 flex items-center gap-3">
                  <Scale className="w-6 h-6 text-purple-600" />
                  10. General Provisions
                </h2>
                
                <div className="space-y-6">
                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Entire Agreement</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      This Agreement constitutes the entire agreement between You and Us and supersedes all prior written and oral agreements.
                    </p>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Severability</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      If any provision is held to be unenforceable, the remaining provisions will remain in effect.
                    </p>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Force Majeure</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      We shall not be liable for delays or failures in performance due to events beyond Our control, including but not limited to acts of God, government actions, war, strikes, pandemics, earthquakes, floods, Internet outages, hardware failures, or hacking attacks.
                    </p>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Assignment</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      You may not assign any rights or obligations without Our prior written consent. We may assign this Agreement in connection with a merger, acquisition, or sale of assets.
                    </p>
                  </div>

                  <div className="bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800 rounded-lg p-6">
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-3">Arbitration, Governing Law and Jurisdiction</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm mb-3">
                      Any unresolved dispute shall be settled in accordance with the laws of India, in particular the <strong>Arbitration and Conciliation Act, 1996</strong> by appointing a sole arbitrator with mutual consent.
                    </p>
                    <ul className="space-y-2 text-slate-600 dark:text-slate-400 text-sm">
                      <li>• The decision of the arbitrator shall be final</li>
                      <li>• The venue and seat of arbitration shall only be at <strong>Bengaluru, India</strong></li>
                      <li>• The Courts at Bengaluru shall have exclusive jurisdiction</li>
                      <li>• The language of arbitration shall be English</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Waiver</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                      No failure or delay by IntPurple Technologies LLP in exercising any right will constitute a waiver of that right.
                    </p>
                  </div>
                </div>
              </section>

              {/* Contact Section */}
              <section className="bg-gradient-to-br from-brand-primary to-purple-600 rounded-xl p-8 text-white">
                <h2 className="text-2xl font-black mb-4 flex items-center gap-3">
                  <Mail className="w-6 h-6" />
                  Contact Information
                </h2>
                <p className="mb-6 opacity-90">
                  If you have any questions or to send notices of violations to this Agreement, please contact us:
                </p>
                
                <div className="bg-white/10 backdrop-blur-sm rounded-lg p-6">
                  <p className="font-semibold text-lg mb-3">Intpurple Technologies LLP</p>
                  <p>
                    <strong>Email:</strong> <a href="mailto:contact@intpurple.com" className="hover:underline">contact@intpurple.com</a>
                  </p>
                </div>
              </section>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
}